// COptionsPropertiesDlg.h
//*****************************************************************************

#ifndef _COptionsPropertiesDlg_H_
#define _COptionsPropertiesDlg_H_

#include "stdafx.h"
#include "afxwin.h"

#if _MSC_VER > 1000
#pragma once
#endif

//*****************************************************************************
// COptionsPropertiesDlg class
class COptionsPropertiesDlg : public CDialog
{
	DECLARE_DYNAMIC(COptionsPropertiesDlg)

// Dialog data
public:
	enum { IDD = IDD_OPTIONS_PROPERTIES_DLG };

// Member variables
private:
	CButton m_AutoGenerateDontOverwriteCheck;
	CButton m_AutoGenerateTitleCheck;
	CButton m_AutoGenerateTagsCheck;
	CButton m_AutoGenerateAuthorCheck;
	CButton m_AutoGenerateSubjectCheck;
		
// Public methods
public:
	COptionsPropertiesDlg(CWnd* pParent = NULL);
	virtual ~COptionsPropertiesDlg();
	BOOL ValidateAndProcess();

// Private methods
private:

// Override
protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	virtual BOOL OnInitDialog();

// Messages
protected:
	DECLARE_MESSAGE_MAP()
public:
	CEdit m_txtMaximumFiles;
};

#endif