// COptionsPropertiesDlg.cpp 
//*****************************************************************************

#include "stdafx.h"
#include "Benubird.h"
#include "COptionsPropertiesDlg.h"
#include "COptionsDefs.h"
#include "MainFrm.h"
#include "CRegistry.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

extern int g_nMaximumFileCount;

IMPLEMENT_DYNAMIC(COptionsPropertiesDlg, CDialog)

//*****************************************************************************
// Message map
BEGIN_MESSAGE_MAP(COptionsPropertiesDlg, CDialog)
END_MESSAGE_MAP()
//*****************************************************************************
COptionsPropertiesDlg::COptionsPropertiesDlg(CWnd* pParent /*=NULL*/)
	: CDialog(COptionsPropertiesDlg::IDD, pParent)
{
}
//*****************************************************************************
COptionsPropertiesDlg::~COptionsPropertiesDlg()
{
}
//*****************************************************************************
void COptionsPropertiesDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_OPT_AUTO_GENERATE_DONTOVERWRITE_CHECK, m_AutoGenerateDontOverwriteCheck);
	DDX_Control(pDX, IDC_OPT_AUTO_GENERATE_TITLE_CHECK, m_AutoGenerateTitleCheck);
	DDX_Control(pDX, IDC_OPT_AUTO_GENERATE_TAGS_CHECK, m_AutoGenerateTagsCheck);
	DDX_Control(pDX, IDC_OPT_AUTO_GENERATE_AUTHOR_CHECK, m_AutoGenerateAuthorCheck);
	DDX_Control(pDX, IDC_OPT_AUTO_GENERATE_SUBJECT_CHECK, m_AutoGenerateSubjectCheck);
	DDX_Control(pDX, IDC_OPT_EDIT_MAXIMUM_FILES, m_txtMaximumFiles);
}
//*****************************************************************************
BOOL COptionsPropertiesDlg::ValidateAndProcess()
{
	int lIntValue;
	CWinApp* lApp;
	int lCheck;

	lApp = AfxGetApp();
	
	lCheck = m_AutoGenerateDontOverwriteCheck.GetCheck();
	lApp->WriteProfileInt(kOptions, kAutoGenerateDontOverwrite, lCheck);

	lCheck = m_AutoGenerateTitleCheck.GetCheck();
	lApp->WriteProfileInt(kOptions, kAutoGenerateTitle, lCheck);

	lCheck = m_AutoGenerateTagsCheck.GetCheck();
	lApp->WriteProfileInt(kOptions, kAutoGenerateTags, lCheck);

	lCheck = m_AutoGenerateAuthorCheck.GetCheck();
	lApp->WriteProfileInt(kOptions, kAutoGenerateAuthor, lCheck);

	lCheck = m_AutoGenerateSubjectCheck.GetCheck();
	lApp->WriteProfileInt(kOptions, kAutoGenerateSubject, lCheck);

	TCHAR strTmp[10];
	m_txtMaximumFiles.GetWindowText(strTmp,10);
	lIntValue = _wtoi(strTmp);
	if(lIntValue == 0)
		lIntValue = DEFAULT_MAXIMUM_FILES_COUNT;
	lApp->WriteProfileInt(kOptions, kMaximumFiles, lIntValue);

	g_nMaximumFileCount = lIntValue;
	
	return TRUE;
}
//*****************************************************************************
BOOL COptionsPropertiesDlg::OnInitDialog()
{
	CDialog::OnInitDialog();

	int lIntValue;
	CWinApp* lApp;
	int lCheck;

	lApp = AfxGetApp();

	lCheck = lApp->GetProfileInt(kOptions, kAutoGenerateDontOverwrite, BST_CHECKED);
	m_AutoGenerateDontOverwriteCheck.SetCheck(lCheck);

	lCheck = lApp->GetProfileInt(kOptions, kAutoGenerateTitle, BST_UNCHECKED);
	m_AutoGenerateTitleCheck.SetCheck(lCheck);

	lCheck = lApp->GetProfileInt(kOptions, kAutoGenerateTags, BST_UNCHECKED);
	m_AutoGenerateTagsCheck.SetCheck(lCheck);

	lCheck = lApp->GetProfileInt(kOptions, kAutoGenerateAuthor, BST_UNCHECKED);
	m_AutoGenerateAuthorCheck.SetCheck(lCheck);

	lCheck = lApp->GetProfileInt(kOptions, kAutoGenerateSubject, BST_UNCHECKED);
	m_AutoGenerateSubjectCheck.SetCheck(lCheck);

	lIntValue = 0;
	lIntValue = lApp->GetProfileInt(kOptions, kMaximumFiles, BST_UNCHECKED);
	if(lIntValue == 0)
		lIntValue = DEFAULT_MAXIMUM_FILES_COUNT;

	CString strTmp;
	strTmp.Format(_T("%d"),lIntValue);
	m_txtMaximumFiles.SetWindowText(strTmp.GetBuffer());

	return TRUE;
}
