//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Benubird.rc
//
#define IDOK2                           2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUT_DLG                   100
#define IDS_MAIN_TOOLBAR                101
#define IDS_UNKNOWN_ERROR               102
#define IDS_ZIP_FILES_FILTER            103
#define IDS_IMPORT_SUCCESS_MSG          104
#define IDS_UPDATE_AVAILABLE            105
#define IDS_UPDATE_NONE                 106
#define IDS_UPDATE_ERROR_CONNECTION     107
#define IDS_UPDATE_ERROR_GENERAL        108
#define IDS_CHECK_FOR_UPDATES           109
#define IDS_SAVE_OUTPUT_AS              110
#define IDS_PATH_STR                    111
#define IDS_IMPORT_SUCCESS_ONE_FILE     112
#define IDS_FILE_CHANGE_MSG_TITLE       113
#define IDS_FILE_CHANGE_MSG             114
#define IDS_STRING115                   115
#define IDR_PDF_FILETYPE                115
#define IDR_PDFTYPE                     115
#define IDR_PDF_TYPE                    115
#define IDS_APP_TITLE_PRO               116
#define IDR_LIBRARY_TYPE                116
#define IDR_MAINFRAME                   128
#define IDR_BenubirdTYPE                129
#define IDS_N_FILES_ADDED_SUCCESS       129
#define IDS_MANAGE_TAGS_EDITTAGS_CONFIRMATION 130
#define IDR_POPUP_TOOLBAR               131
#define IDS_MAJORFILTER_ALL_EXTS        131
#define IDS_MAJORFILTER_DOC_EXTS        132
#define IDS_MAJORFILTER_PRES_EXTS       133
#define IDS_MAJORFILTER_SPREAD_EXTS     134
#define IDS_MAJORFILTER_IMAGE_EXTS      135
#define IDD_DOCUMENTPROPERTIES          135
#define IDS_AUTHOR_STR                  136
#define IDD_PROPERTIES_DESC             136
#define IDS_CATEGORY_STR                137
#define IDD_PROPERTIES_SECURITY         137
#define IDS_DATEADDED_STR               138
#define IDD_PROPERTIES_FONTS            138
#define IDS_DATECREATED_STR             139
#define IDD_PROPERTIES_INITIAL_VIEW     139
#define IDS_DATEMODIFIED_STR            140
#define IDD_PROPERTIES_CUSTOM           140
#define IDS_DESCRIPTION_STR             141
#define IDD_SECURITY_PASSWORD           141
#define IDS_FILETYPE_STR                142
#define IDD_REQUEST_PASSWORD            142
#define IDS_LASTOPENED_STR              143
#define IDS_FILENAME_STR                144
#define IDS_SIZE_STR                    145
#define IDS_SUBJECT_STR                 146
#define IDB_WORKSPACE                   147
#define IDS_TAGS_STR                    147
#define IDS_TITLE_STR                   148
#define IDS_CONTAINS_STR                149
#define IDS_DOESNOTCONTAINS_STR         150
#define IDS_IS_STR                      151
#define IDS_ISNOT_STR                   152
#define IDS_STARTSWITH_STR              153
#define IDS_ENDSWITH_STR                154
#define IDS_ISGREATERTHAN_STR           155
#define IDS_ISLESSTHAN_STR              156
#define IDS_ISINRANGE_STR               157
#define IDS_ISAFTER_STR                 158
#define IDS_ISBEFORE_STR                159
#define IDD_NEW_COLLECTION_DLG          160
#define IDD_GET_TEXT_DLG                160
#define IDS_TECH_PREVIEW_END_LINK       160
#define IDB_BENUBIRD_BMP                161
#define IDD_ALERT_DLG                   161
#define IDS_WFS_ALL                     161
#define IDD_DIALOG1                     162
#define IDR_TOOLBAR_ADD_MENU            163
#define IDR_TOOLBAR_ACTIONS_MENU        164
#define IDR_FIND_OPTIONS_MENU           165
#define IDR_DOCUMENT_FILE_MENU          166
#define IDR_DOCUMENT_LIST_MENU          166
#define IDD_BROWSER_DIALOG              167
#define IDD_BROWSER_DLG                 167
#define IDD_TAGS_DLG                    168
#define IDD_MANAGE_TAGS_DLG             169
#define IDB_ABOUT_BMP                   170
#define IDD_MANAGE_CATEGORIES_DLG       170
#define IDD_OPTIONS_DLG                 171
#define IDD_OPTIONS_GENERAL_TAB_DLG     172
#define IDD_OPTIONS_GENERAL_DLG         172
#define IDD_OPTIONS_NOTIFICATIONS_TAB_DLG 174
#define IDD_OPTIONS_NOTIFICATIONS_DLG   174
#define IDR_LICENSE_TEXT                175
#define IDD_BURN_TO_DISC_DLG            176
#define IDR_STOP_BTN_PNG                187
#define IDR_HTML1                       189
#define IDR_LICENSE_HTML                189
#define IDD_WATCHED_FOLDER_SETTINGS_DLG 190
#define IDR_TRAY_MENU                   195
#define IDD_ADD_MULTIPLE_TAGS_DLG       197
#define IDD_BROWSE_FOLDER_DLG           198
#define IDB_BITMAP1                     199
#define IDB_DOC_THUMB_BMP               199
#define IDD_MULTIPLE_PROFILE_INFORMATION_DLG 200
#define IDB_RB_FILE_SMALL_BMP           200
#define IDB_RB_MENU_SMALL_BMP           200
#define IDB_RB_FILE_LARGE_BMP           201
#define IDD_INCLUDE_FILE_TYPES_DLG      201
#define IDB_RB_MENU_LARGE_BMP           201
#define IDB_RB_HOME_SMALL_BMP           202
#define IDB_RB_HOME_LARGE_BMP           203
#define IDB_RB_MANAGE_SMALL_BMP         204
#define IDD_COPY_COLLECTION_DLG         204
#define IDB_RB_MANAGE_LARGE_BMP         205
#define IDB_RB_IMPORT_AND_EXPORT_SMALL_BMP 206
#define IDR_DOCUMENT_LIST_HEADER_MENU   206
#define IDB_RB_IMPORT_AND_EXPORT_LARGE_BMP 207
#define IDB_RB_HELP_LARGE_BMP           208
#define IDB_RB_HELP_SMALL_BMP           209
#define IDR_COLLECTION_MENU             209
#define IDB_RB_MAIN_BMP                 210
#define IDD_SMART_COLLECTIONS_DLG       210
#define IDR_SMART_COLLECTION_MENU       210
#define IDD_MANAGE_WATCHED_FOLDERS_DLG  211
#define IDR_FILTER_MENU                 211
#define IDI_ALERT_WARNING_ICON          213
#define IDD_TAGS_EDITTAG_DLG            213
#define IDI_ALERT_ERROR_ICON            214
#define IDD_DELETE_FILE_DLG             214
#define IDI_ALERT_INFO_ICON             215
#define IDB_BITMAP2                     215
#define IDB_FILE_SMALL_BMP              215
#define IDI_ALERT_QUESTION_ICON         216
#define IDB_BITMAP3                     216
#define IDB_FILE_LARGE_BMP              216
#define IDD_TAGS_SELECTION_DLG          217
#define IDR_UNKNOWN_FILE_ICO            217
#define IDR_UNKNOWN_FILE_ICON           217
#define IDC_DRAG_ENABLE_CUR             218
#define IDB_BITMAP4                     218
#define IDB_COLLECTIONS_BMP             218
#define IDC_CURSOR2                     219
#define IDC_DRAG_DISABLE_CUR            219
#define IDB_BITMAP5                     219
#define IDB_RB_PANELS_                  219
#define IDB_RB_PANELS_MANAGE_BMP        219
#define IDB_BITMAP6                     220
#define IDB_RB_PANELS_HELP_BMP          220
#define IDB_BITMAP7                     221
#define IDB_RB_PANELS_HOME_BMP          221
#define IDB_BITMAP8                     222
#define IDB_RB_PANELS_IMPORT_AND_EXPORT_BMP 222
#define IDD_DIALOG2                     224
#define IDD_MISSING_FILE_DLG            224
#define IDD_DIALOG3                     226
#define IDD_MISSING_FILES_DLG           226
#define IDR_AVI1                        228
#define IDR_ANIMATION_AVI               228
#define IDR_EMPTY_FILE_ICON             230
#define IDI_ICON1                       231
#define IDI_ICON2                       232
#define IDI_ALERT_HAND_ICON             232
#define IDR_WORKSPACE_NOTIFY            233
#define IDD_REGISTER_BENUBIRD_PRO_DLG   234
#define IDD_CONFIRM_OVERWRITE           235
#define IDD_SPLASH_SCREEN_DLG           236
#define IDB_SPLASH_SCREEN_BMP           237
#define IDD_DIALOG4                     238
#define IDD_LICENSE_DLG                 238
#define IDD_EXPORT_ZIP_DLG              239
#define IDD_DIALOG5                     240
#define IDD_EXPORT_ZIP_CONFIRM_PASSWORD_DLG 240
#define IDD_ABOUT_TAB_ABOUT             241
#define IDB_BITMAP9                     242
#define IDB_DEBENU_LOGO_BMP             242
#define IDB_BITMAP10                    243
#define IDB_LIBRARY_OUTLOOK_BAR_PANEL_BMP 243
#define IDD_IMPORT_FROM_ZIP_DLG         244
#define IDD_RENAME_FILE_DIALOG          245
#define IDD_RENAME_FILE_DLG             245
#define IDD_DIALOG_SET_FILE_PROPERTIES  247
#define IDD_CONVERT2PDF_DLG             250
#define IDD_CHANGED_FILES_DLG           252
#define IDC_PASSWORD                    255
#define IDB_RB_UPGRADE_LARGE            258
#define IDB_RB_UPGRADE_SMALL            259
#define IDD_PDF_PREVIEW                 260
#define IDR_DOCUMENT_LIST_MENU_DIRECT   261
#define IDI_IN_WORKSPACE                303
#define IDR_STATUSBAR                   306
#define IDB_RB_PDF_LARGE_BMP            308
#define IDB_RB_PDF_SMALL_BMP2           309
#define IDB_RB_PDF_SMALL_BMP            309
#define IDD_LIBRARY_SETTING             310
#define IDD_TRIAL_NOTIFICATION          315
#define IDB_BITMAP11                    316
#define IDR_AVI2                        317
#define IDC_PDFFILE                     1001
#define IDC_ADD                         1006
#define IDC_DELETE                      1007
#define IDC_STATICTAB                   1019
#define IDC_TITLE                       1020
#define IDC_AUTHOR                      1021
#define IDC_SUBJECT                     1022
#define IDC_KEYWORDS                    1023
#define IDC_CREATOR                     1025
#define IDC_PRODUCER                    1026
#define IDC_CREATED                     1027
#define IDC_MODIFIED                    1028
#define IDC_PDF_VERSION                 1030
#define IDC_PAGECOUNT                   1031
#define IDC_FASTWEB                     1032
#define IDC_SECURITYMETHOD              1033
#define IDC_CHANGESETTINGS              1034
#define IDC_ALERT_ICON                  1040
#define IDC_COMPANY_URL                 1041
#define IDC_COMPANY_LINK_BTN            1041
#define IDC_NEW_COLLECTION_EDIT         1042
#define IDC_MANAGE_TAGS_ADD_BTN         1042
#define IDC_TOOLBAR_ADD_BTN             1043
#define IDC_MANAGE_TAGS_EDIT_BTN        1043
#define IDC_ALERT_BTN1                  1043
#define IDC_TOOLBAR_ACTIONS_BTN         1044
#define IDC_MANAGE_TAGS_DELETE_BTN      1044
#define IDC_ALERT_BTN2                  1044
#define IDC_EDIT1                       1045
#define IDC_MANAGE_TAGS_LIST            1045
#define IDC_ALERT_MESSAGE               1045
#define IDC_FIND_OPTIONS_BTN            1046
#define IDC_MANAGE_TAGS_EXPORT_BTN      1046
#define IDC_EDIT6                       1046
#define IDC_MPI_AUTHOR_EDIT             1046
#define IDC_WF_AUTHOR_EDIT              1046
#define IDC_PASS_CHANGE1                1046
#define ID_BURN_TO_CD_DVD               1047
#define IDC_MANAGE_TAGS_IMPORT_BTN      1047
#define IDC_EDIT7                       1047
#define IDC_MPI_TAGS_EDIT               1047
#define IDC_WF_CAT_EDIT                 1047
#define IDC_PASS_CHANGE2                1047
#define IDC_EDIT8                       1048
#define IDC_MPI_SUBJECT_EDIT            1048
#define IDC_WF_SUBJECT_EDIT             1048
#define IDC_PASS_CHANGE_DOC             1048
#define IDC_MPI_CATEGORY_EDIT           1049
#define IDC_WF_TAGS_EDIT                1049
#define IDC_PASS_OPEN1                  1049
#define IDC_MPI_COMMENTS_EDIT           1050
#define IDC_EDIT10                      1050
#define IDC_WF_COMMENTS_EDIT            1050
#define IDC_STATICGRID                  1050
#define IDC_PASS_OPEN2                  1050
#define IDC_SHOW_TAGS_BTN               1051
#define ID_SHOW_TAGS                    1051
#define IDC_PASS_OPEN_DOC               1051
#define IDC_SHOW_BROWSER_BTN            1052
#define IDC_BROWSER_PANEL1_COMBO        1052
#define IDC_NAVIGATIONTAB               1052
#define IDC_BROWSER_PANEL2_COMBO        1053
#define IDC_PAGELAYOUT                  1053
#define IDC_BROWSER_PANEL3_COMBO        1054
#define IDC_MAGNIFICATION               1054
#define IDC_BROWSER_PANEL4_COMBO        1055
#define IDC_OPENTOPAGE                  1055
#define IDC_HIDE_TAGS_AND_BROWSER_BTN   1056
#define IDC_TOTALPAGES                  1056
#define IDC_BROWSER_PANEL1_LIST         1057
#define IDC_HIDETOOLBAR                 1057
#define IDC_BROWSER_PANEL2_LIST         1058
#define IDC_HIDEMENUBAR                 1058
#define IDC_BROWSER_PANEL3_LIST         1059
#define IDC_HIDEWINDOW                  1059
#define IDC_BROWSER_PANEL4_LIST         1060
#define IDC_BROWSER_PANEL3_LIST2        1060
#define IDC_FITWINDOW                   1060
#define IDC_CENTERWINDOW                1061
#define IDC_MANAGE_CATEGORIES_LIST      1062
#define IDC_FULLSCREEN                  1062
#define IDC_MANAGE_CATEGORIES_ADD_BTN   1063
#define IDC_DOCUMENTTITLE               1063
#define IDC_MANAGE_CATEGORIES_EDIT_BTN  1064
#define IDC_MANAGE_CATEG_DELETE_BTN     1065
#define IDC_MANAGE_CATEGORIES_IMPORT_BTN 1066
#define IDC_MANAGE_CATEGORIES_EXPORT_BTN 1067
#define IDC_OPTIONS_TAB                 1068
#define IDC_STATIC_PRINTING             1068
#define IDC_CHECK1                      1069
#define IDC_STATIC_CHANGING             1069
#define IDC_MPI_CATEGORY_CHECK          1070
#define IDC_OPT_UNSORTED_FILTER_CATEGORIES_CHECK 1070
#define IDC_OPT_GENERAL_IGNORE_NOEXT_FILES_CHECKIDC_CHECK 1070
#define IDC_OPT_GENERAL_IGNORE_NOEXT_FILES_CHECK 1070
#define IDC_STATIC_ACC                  1070
#define IDC_CHECK3                      1071
#define IDC_MPI_TITLE_CHECK             1071
#define IDC_OPT_UNSORTED_FILTER_COLLECTIONS_CHECK 1071
#define IDC_STATIC_COPYING              1071
#define IDC_BUTTON1                     1072
#define IDC_CHECK6                      1072
#define IDC_MPI_TAGS_CHECK              1072
#define IDC_STATIC_COPYING_ACC          1072
#define IDC_CHECK4                      1073
#define IDC_BUTTON2                     1073
#define IDC_INFO_NEXT_BTN               1073
#define IDC_MUL_PROF_INFO_EDIT_TAGS_BTN 1073
#define IDC_MPI_EDIT_TAGS_BTN           1073
#define IDC_SS_ENTER_SERIAL_BTN         1073
#define IDC_ABOUT_ENTER_SERIAL_NUMBER_BTN 1073
#define IDC_DELETE_BUTTON               1073
#define IDC_DELESECT_ALL                1073
#define IDC_DESELECT_ALL                1073
#define IDC_STATIC_PAGEEXTR             1073
#define IDC_CHECK5                      1074
#define IDC_BUTTON5                     1074
#define IDC_MPI_SUBJECT_CHECK           1074
#define IDC_STATIC_COMMENTING           1074
#define IDC_COMBO1                      1075
#define IDC_BUTTON4                     1075
#define IDC_BUTTON_SKIP                 1075
#define IDC_STATIC_FORMFILLING          1075
#define IDC_PROGRESS1                   1076
#define IDC_COMBO2                      1076
#define IDC_WFOLDSET_FREQUENCY_COMBO    1076
#define IDC_BUTTON_RENAME               1076
#define IDC_STATIC_SIGNING              1076
#define IDC_COMBO3                      1077
#define IDC_BUTTON_REPLACE_OLDER        1077
#define IDC_STATIC_TEMPLATING           1077
#define IDC_COMBO4                      1078
#define IDC_SC_COMBO2                   1078
#define IDC_SC_VERBS1_COMBO             1078
#define IDC_PRINTING_ALLOWED            1078
#define IDC_COMBO5                      1079
#define IDC_SC_VERBS2_COMBO             1079
#define IDC_CHANGES_ALLOWED             1079
#define IDC_RADIO1                      1080
#define IDC_MATCH_ALL_RADIO             1080
#define IDC_COMBO6                      1080
#define IDC_WF_ALL_FILE_TYPES_RADIO     1080
#define IDC_SC_VERBS3_COMBO             1080
#define IDC_BUTTON_AUTO_RENAME          1080
#define IDC_RADIO_ALL_FILES             1080
#define IDC_ENABLE_COPYING              1080
#define IDC_RADIO2                      1081
#define IDC_MATCH_ANY_RADIO             1081
#define IDC_WF_ONLY_THESE_FILE_TYPES_RADIO 1081
#define IDC_SC_VERBS4_COMBO             1081
#define IDC_BUTTON_AUTO_RENAME2         1081
#define IDC_BUTTON_COPY_NEW             1081
#define IDC_RADIO_SOME_FILES            1081
#define IDC_ENABLE_TEXTACCESS           1081
#define IDC_LIST1                       1082
#define IDC_TAGS_LIST                   1082
#define IDC_MWF_LIST                    1082
#define IDC_TS_AVAILABLE_TAGS_LIST      1082
#define IDC_SC_VERBS5_COMBO             1082
#define IDC_FILE_LIST                   1082
#define IDC_CHANGED_FILE_LIST           1082
#define IDC_ENCRYPTIONLEVEL             1082
#define IDC_ALPHABETICAL_TAGS_BTN       1083
#define IDC_TS_SELECTED_TAGS_LIST       1083
#define IDC_SC_VERBS6_COMBO             1083
#define IDC_POPULAR_TAGS_BTN            1084
#define IDC_BUTTON6                     1084
#define IDC_SC_VERBS7_COMBO             1084
#define IDC_BROWSER_PANEL1_UNSELECT_BTN 1085
#define IDC_BUTTON7                     1085
#define IDC_SC_VERBS8_COMBO             1085
#define IDC_BROWSER_PANEL2_UNSELECT_BTN 1086
#define IDC_BUTTON8                     1086
#define IDC_SC_ADD_BTN                  1086
#define IDC_SC_ADD1_BTN                 1086
#define IDC_BROWSER_PANEL3_UNSELECT_BTN 1087
#define IDC_SC_ADD2_BTN                 1087
#define IDC_BROWSER_PANEL4_UNSELECT_BTN 1088
#define IDC_SC_ADD3_BTN                 1088
#define IDC_SC_ADD4_BTN                 1089
#define IDC_MANAGE_TAGS_BTN             1090
#define IDC_SC_ADD5_BTN                 1090
#define IDC_SELECTED_TAGS_ST            1091
#define IDC_SC_ADD6_BTN                 1091
#define IDC_PROPNAME                    1091
#define IDC_SC_ADD7_BTN                 1092
#define IDC_PROPVALUE                   1092
#define IDC_SC_ADD8_BTN                 1093
#define IDC_PROPSLIST                   1093
#define IDC_SC_VERBS9_COMBO             1094
#define IDC_SC_ADD9_BTN                 1095
#define IDC_GET_INFO_TAB                1096
#define IDC_SC_VERBS10_COMBO            1096
#define IDC_EDIT2                       1097
#define IDC_SC_LIMIT_TO_EDIT            1097
#define IDC_COMPANY_EDIT                1097
#define IDC_EDIT_PASSWORD               1097
#define IDC_FILENAME_EDIT               1097
#define IDC_EDIT3                       1098
#define IDC_INFO_TAGS_EDIT              1098
#define IDC_SC_ADD10_BTN                1098
#define IDC_EDIT4                       1099
#define IDC_INFO_SUBJECT_EDIT           1099
#define IDC_EDIT5                       1100
#define IDC_INFO_CATEGORIES_EDIT        1100
#define IDC_BUTTON3                     1101
#define IDC_INF_ADDITIONAL_METADATA_BTN 1101
#define IDC_SS_TRY_NOW_BTN              1101
#define IDC_ABOUT_PURCHASE_LICENSE_ONLINE_BTN 1101
#define IDC_ADD_TAGS_EDIT               1102
#define IDC_WF_EDIT_CATEGORIES_BTN      1102
#define IDC_ADD_MULTIPLE_BTN            1103
#define IDC_ADD_MULTIPLE_TAGS_EDIT      1104
#define IDC_TREE1                       1105
#define IDC_BF_SHELL_TREE               1105
#define IDC_OPTIONS_TREE                1105
#define IDC_COMBO10                     1106
#define IDC_WF_EDIT_TAGS_BTN            1106
#define IDC_INCLUDE_FILE_TYPES_LIST     1106
#define IDC_SC_LIMIT_TO_COMBO           1106
#define IDC_TS_MANAGE_TAGS_BTN          1107
#define IDC_WF_CHOOSE_FILE_TYPES_BTN    1107
#define IDC_MWF_ADD_BTN                 1108
#define IDC_OPTIONS_PANEL               1108
#define IDC_MWF_EDIT_BTN                1109
#define IDC_OPT_INTERFACE_COLOR_SCHEME_COMBO 1109
#define IDC_MWF_REMOVE_BTN              1110
#define IDC_INFO_EDIT_CATEGORIES_BTN    1110
#define IDC_CS_MANAGE_CATEGORIES_BTN    1111
#define IDC_INFO_EDIT_TAGS_BTN          1111
#define IDC_CS_AVAILABLE_CATEGORIES_LIST 1112
#define IDC_INFO_CHANGE_OPEN_WITH_BTN   1112
#define IDC_CS_SELECTED_CATEGORIES_LIST 1113
#define IDC_WF_LOCATION_LABEL           1113
#define IDC_CS_ADD_BTN                  1114
#define IDC_WF_INCLUDE_LABEL            1114
#define IDC_CS_REMOVE_BTN               1115
#define IDC_WF_TAGS_LABEL               1115
#define IDC_TS_ADD_BTN                  1116
#define IDC_WF_CATEGORIES_LABEL         1116
#define IDC_TS_REMOVE_BTN               1117
#define IDC_WF_COLLECTION_LABEL         1117
#define IDC_WF_FREQUENCY_LABEL          1118
#define IDC_BF_INCLUDE_SUBFOLDERS_CHECK 1119
#define IDC_SC_COMBO1                   1120
#define IDC_SC_NOUNS1_COMBO             1120
#define IDC_SC_EDIT                     1121
#define IDC_SC_VALUE1_EDIT              1121
#define IDC_SC_UNIT                     1122
#define IDC_SC_REMOVE_BTN               1123
#define IDC_SC_REMOVE1_BTN              1123
#define IDC_WFS_BROWSE_BTN              1124
#define IDC_SC_NOUNS2_COMBO             1124
#define IDC_WFS_LOCATION                1125
#define IDC_SC_UNIT2                    1125
#define IDC_WFS_INCLUDE                 1126
#define IDC_SC_REMOVE2_BTN              1126
#define IDC_INFO_FILE_STATIC            1127
#define IDC_SUMMARY_FILE_STATIC         1127
#define IDC_SC_VALUE2_EDIT              1127
#define IDC_INFO_PREVIOUS_BTN           1128
#define IDC_SC_NOUNS3_COMBO             1128
#define IDC_INFO_TITLE_EDIT             1129
#define IDC_SC_UNIT3                    1129
#define IDC_INFO_AUTHOR_EDIT            1130
#define IDC_SC_REMOVE3_BTN              1130
#define IDC_SUMMARY_LOCATION_STATIC     1131
#define IDC_SC_VALUE3_EDIT              1131
#define IDC_OPT_GENERAL_LOAD_ON_STARTUP_CHECK 1132
#define IDC_SC_NOUNS4_COMBO             1132
#define IDC_OPT_GENERAL_SHOW_ICON_IN_SYSTEM_TRAY_CHECK 1133
#define IDC_SC_UNIT4                    1133
#define IDC_OPT_GENERAL_MINIMIZE_TO_SYSTEM_TRAY_CHECK 1134
#define IDC_SC_REMOVE4_BTN              1134
#define IDC_OFM_CHANGE_BTN              1135
#define IDC_OPT_FILE_MANAGER_CHANGE_BTN 1135
#define IDC_SC_VALUE4_EDIT              1135
#define IDC_OFM_LOCATION_EDIT           1136
#define IDC_OPT_FILE_MANAGER_LOCATION_EDIT 1136
#define IDC_SC_NOUNS5_COMBO             1136
#define IDC_OPT_REPOSITORY_LOCATION_EDIT 1136
#define IDC_OFM                         1137
#define IDC_OFM_COPY_FILES_TO_FOLDER_CHECK 1137
#define IDC_OPT_FILE_MANAGER_COPY_FILES_TO_FOLDER_CHECK 1137
#define IDC_SC_UNIT5                    1137
#define IDC_OPT_WORKSPACE_LOCATION_EDIT 1137
#define IDC_OPTIONS_NOTIFICATION_WHEN_ADD_SILENTLY_CHECK 1138
#define IDC_OPT_NOTIFY_WHEN_ADD_SILENTLY_CHECK 1138
#define IDC_SC_REMOVE5_BTN              1138
#define IDC_OPT_NOTIFY_WHEN_ADD_DIRECTLY_CHECK 1139
#define IDC_SC_VALUE5_EDIT              1139
#define IDC_OPT_NOTIFY_WHEN_UPDATE_AVAILABLE_CHECK 1140
#define IDC_SC_NOUNS6_COMBO             1140
#define IDC_OPT_CHECK_FOR_UPDATES_CHECK 1141
#define IDC_SC_UNIT6                    1141
#define IDC_OPT_CHECK_FOR_UPDATES_COMBO 1142
#define IDC_SC_REMOVE6_BTN              1142
#define IDC_SUMMARY_SIZE_STATIC         1143
#define IDC_SC_VALUE6_EDIT              1143
#define IDC_SUMMARY_SIZE_ON_DISK_STATIC 1144
#define IDC_SC_NOUNS7_COMBO             1144
#define IDC_SC_UNIT7                    1145
#define IDC_SC_REMOVE7_BTN              1146
#define IDC_SC_VALUE7_EDIT              1147
#define IDC_SC_NOUNS8_COMBO             1148
#define IDC_SC_UNIT8                    1149
#define IDC_SC_REMOVE8_BTN              1150
#define IDC_SC_VALUE8_EDIT              1151
#define IDC_SC_NOUNS9_COMBO             1152
#define IDC_SC_UNIT9                    1153
#define IDC_SC_REMOVE9_BTN              1154
#define IDC_SC_VALUE9_EDIT              1155
#define IDC_SC_NOUNS10_COMBO            1156
#define IDC_SC_UNIT10                   1157
#define IDC_SC_REMOVE10_BTN             1158
#define IDC_SC_EDIT10                   1159
#define IDC_SC_VALUE10_EDIT             1159
#define IDC_SC_LIMIT_TO_CHECK           1160
#define IDC_SUMMARY_CREATED_STATIC      1161
#define IDC_SUMMARY_MODIFIED_STATIC     1162
#define IDC_SUMMARY_ACCESSED_STATIC     1163
#define IDC_SUMMARY_OPENSWITH_STATIC    1164
#define IDC_SUMMARY_FILETYPE_STATIC     1165
#define IDC_TAGNAME_EDIT                1166
#define IDC_WATCHED_SETTINGS_COLL_COMBO 1167
#define IDC_LIST4                       1170
#define IDC_MOVE_TO_RECYCLE_BIN_BTN     1171
#define IDC_KEEP_FILE_BTN               1172
#define IDC_SC_MATCH_THE_FOLLOWING_RULE_CHECK 1173
#define IDC_SC_OK_BTN                   1174
#define IDC_SC_CANCEL                   1175
#define IDC_SC_CANCEL_BTN               1175
#define IDC_WATCHF_INCLUDESUBFOLDERS_CHECK 1176
#define IDC_WFS_TAGS_STATIC             1177
#define IDC_GETINFO_INFO_APPLY_METADATA_CHECK 1178
#define IDC_ABOUT_VERSION               1179
#define IDC_MPI_AUTHOR_CHECK            1180
#define IDC_MPI_TITLE_EDIT              1181
#define IDC_INFO_COMMENTS_EDIT          1182
#define IDC_OPT_UNSORTED_FILTER_AUTHOR_CHECK 1183
#define IDC_OPT_UNSORTED_FILTER_TITLE_CHECK 1184
#define IDC_OPT_UNSORTED_FILTER_SUBJECT_CHECK 1185
#define IDC_OPT_UNSORTED_FILTER_TAGS_CHECK 1186
#define IDC_UPDATE_LOCATION_BTN         1187
#define IDC_LIST5                       1190
#define IDC_PREVIEW_STATIC              1191
#define IDC_PREVIEW_STATIC2             1192
#define IDC_PREVIEW_ICON                1192
#define IDC_MPI_COMMENTS_CHECK          1192
#define IDC_WF_TITLE_CHECK              1193
#define IDC_WF_AUTHOR_CHECK             1194
#define IDC_WF_SUBJECT_CHECK            1195
#define IDC_WF_CAT_CHECK                1196
#define IDC_WF_TAGS_CHECK               1197
#define IDC_WF_COMMENTS_CHECK           1198
#define IDC_WF_TITLE_EDIT               1199
#define ID_ACTIVATE_BTN                 1200
#define IDC_VISIT_DEBENU_BTN            1201
#define IDC_SERIAL_NUMBER_EDIT          1202
#define IDC_ALERT_BTN3                  1203
#define IDC_OPT_GENERAL_IGNORE_TMP_FILES_CHECK 1204
#define IDC_OPT_GENERAL_IGNORE_WIN_FILES_CHECK 1205
#define IDC_BUTTON_REPLACE              1206
#define IDC_CHECK_APPLY_TO_ALL          1207
#define IDC_STATIC_FILENAME1            1208
#define IDC_STATIC_FILE_DETAILS1        1209
#define IDC_STATIC_FILENAME2            1210
#define IDC_STATIC_FILE_DETAILS2        1211
#define IDC_ALERT_CHECK                 1223
#define IDC_SS_BUY_NOW_BTN              1224
#define IDC_SS_TEXT1_STATIC             1225
#define IDC_SS_TEXT2_STATIC             1226
#define IDC_NAME_EDIT                   1227
#define IDC_LICENSE_EDIT                1228
#define IDC_SOURCE_COMBO                1229
#define IDC_SOURCE_FILES_COMBO          1229
#define IDC_COLLECTIONS_COMBO           1230
#define IDC_CHECK_ENCRYPT               1231
#define IDC_CHECK_INCLUDE_DB            1232
#define IDC_EDIT_OUTPUT                 1233
#define IDC_SC_VALUE1_BUTTON            1235
#define IDC_ABOUT_TAB                   1236
#define IDC_DEBENU_URL_BTN              1237
#define IDC_ABOUT_VERSION_STATIC        1238
#define IDC_ABOUT_LICENSED_TO_EDIT      1239
#define IDC_ABOUT_LICENSE_AGREEMENT_BTN 1240
#define IDC_ABOUT_TRIAL_VERSION_STATIC  1241
#define IDC_ABOUT_TRIAL_TEXT_STATIC     1242
#define IDC_COMBO_ONCOPY_ACTION         1243
#define IDC_OPT_ON_ADD_ACTION_COMBO     1243
#define IDC_EDIT_INPUT                  1244
#define IDC_OPT_ON_CHANGE_ACTION_COMBO  1244
#define IDC_CHECK_PASSWORD              1245
#define IDC_BUTTON_OPTIONS              1246
#define IDC_CHECK_INCLUDE_SUBFOLDERS    1247
#define IDC_COMBO_FILE_OPERATION        1248
#define IDC_STATIC_FILE_TYPES           1249
#define IDC_BUTTON_FILE_TYPES           1250
#define IDC_COLLECTION_COMBO            1251
#define IDC_OPT_AUTO_GENERATE_TITLE_CHECK 1252
#define IDC_OPT_AUTO_GENERATE_TAGS_CHECK 1253
#define IDC_OPT_AUTO_GENERATE_AUTHOR_CHECK 1254
#define IDC_OPT_AUTO_GENERATE_AUTHOR_CHECK2 1255
#define IDC_OPT_AUTO_GENERATE_SUBJECT_CHECK 1255
#define IDC_OPT_PDF_HYPERLINKS_CHECK    1255
#define IDC_OPT_PDF_BOOKMARKS_CHECK     1256
#define IDC_OPT_AUTO_GENERATE_SUBJECT_CHECK2 1256
#define IDC_OPT_AUTO_GENERATE_DONTOVERWRITE_CHECK 1256
#define IDC_OPT_PDF_EMBED_SUBSET_CHECK  1257
#define IDC_OPT_PDF_DISPLAY_INFOTAB_CHECK 1258
#define IDC_OPT_PDF_USE_INFO_CHECK      1259
#define IDC_OPT_PDF_PREVIEW_WITH_QUICKPDF_CHECK 1259
#define IDC_OPT_PDF_RENDER_WITH_QUICKPDF_CHECK 1259
#define IDC_OPT_PDF_GSETTINGS_COMBO     1260
#define IDC_PROPERTIES_BUTTON           1261
#define IDC_OPEN_CHECK                  1262
#define IDC_COLL_COMBO                  1263
#define IDC_VERSION_COMBO               1264
#define IDC_FWW_CHECK                   1265
#define IDC_TITLE_EDIT                  1266
#define IDC_AUTHOR_EDIT                 1267
#define IDC_SUBJECT_EDIT                1268
#define IDC_TAGS_EDIT                   1269
#define IDC_SELECT_ALL                  1271
#define IDC_OPT_GENERAL_IGNORE_LNK_FILES_CHECK 1272
#define IDC_PDF_INFO_TEXT               1273
#define IDC_OPT_GENERAL_REPOSITORY_CHECK 1276
#define IDC_OPT_GENERAL_IGNORE_SVN_CHECK 1277
#define IDC_EDIT_PDF_OUTPUT             1278
#define IDC_OPT_PDF_OUTPUT_EDIT         1278
#define IDC_QPL_VERSION                 1279
#define IDC_QPL_VERSION_STATIC          1279
#define IDC_QPL_VERSION_STATIC2         1281
#define IDC_SQL_VERSION_STATIC          1281
#define IDC_RICHEDIT21                  1401
#define IDC_LICENSE_EDIT2               1401
#define IDC_PREVIEW_DC                  1402
#define IDC_EDIT_DEST_DIRECTORY         1404
#define IDC_BUTTON_BROWSER              1405
#define IDC_CHECK_LIBRARYSETTING_USEREPOSITORY 1406
#define IDC_EDIT_LIBRARYSETTING_REPOSITORY 1407
#define IDC_BUTTON_LIBRARYSETTING_SAVE  1408
#define IDC_EDIT_LIBRARYSETTING_WORKSPACE 1409
#define IDC_COMBO_WORKSPACE_TYPE        1410
#define IDC_CHECK_IS_DEFAULT            1411
#define IDC_EDIT_MAXIMUM_FILES          1412
#define IDC_OPT_EDIT_MAXIMUM_FILES      1413
#define IDC_TRIAL_MESSAGE               1414
#define IDC_EDIT_KEYWORD                1415
#define IDC_EDIT_FOLDER                 1415
#define IDC_EDIT_WORD                   1416
#define ID_LIBRARY                      1479
#define ID_LIBRARY_NEW                  1480
#define ID_LIBRARY_OPEN                 1481
#define ID_LIBRARY_IMPORT               1482
#define ID_LIBRARY_EXPORT               1483
#define ID_ADD_FILE                     1500
#define ID_ADD_FOLDER                   1501
#define ID_CREATE_COLLECTIONS           1502
#define ID_CREATE_SMART_COLLECTIONS     1503
#define ID_VIEW_ICONS                   1504
#define ID_VIEW_FILTER                  1505
#define ID_VIEW_TAGS                    1506
#define ID_VIEW_THUMBNAILS              1507
#define ID_VIEW_PREVIEW                 1508
#define ID_VAULT_VIEW                   1509
#define ID_METADATA_TAGS                1510
#define ID_METADATA_CATEGORIES          1511
#define ID_FOLDERS_WATCHED              1512
#define ID_IMPORT_LIBRARY               1513
#define ID_IMPORT_COLLECTION            1514
#define ID_HELP_USER_GUIDE              1515
#define ID_HELP_ONLINE_TUTORIALS        1516
#define ID_PRODUCT_ABOUT                1517
#define ID_PRODUCT_LICENSE_INFORMATION  1518
#define ID_PRODUCT_CHECK_FOR_UPDATES    1519
#define ID_CONTACT_SUPPORT              1520
#define ID_CONTACT_SALES                1521
#define ID_CONTACT_BUG_REPORT           1522
#define ID_UPGRADE_BENUBIRD_PRO         1523
#define ID_EXPORT_LIBRARY               1524
#define ID_ZIP_LIBRARY                  1525
#define ID_COPY_LIBRARY                 1526
#define ID_BURN_LIBRARY                 1527
#define ID_EXPORT_COLLECTION            1528
#define ID_ZIP_COLLECTION               1529
#define ID_COPY_COLLECTION              1530
#define ID_BURN_COLLECTION              1531
#define ID_EXPORT_SELECTION             1532
#define ID_ZIP_SELECTION                1533
#define ID_COPY_SELECTION               1534
#define ID_BURN_SELECTION               1535
#define ID_OPTIONS                      1536
#define ID_SEARCH_FOCUS                 1537
#define ID_SEARCH_EDIT                  1538
#define ID_SEARCH_OPTION                1539
#define ID_SEARCH_OPTION_ALL            1540
#define ID_SEARCH_OPTION_TITLE          1541
#define ID_SEARCH_OPTION_AUTHOR         1542
#define ID_SEARCH_OPTION_SUBJECT        1543
#define ID_SEARCH_OPTION_TAGS           1544
#define ID_LIBRARY_PANEL                1545
#define ID_STATUSBAR_PROGRESS           1546
#define ID_IMPORT_ZIP                   1547
#define ID_IMPORT_FOLDER                1548
#define IDS_IMPORT_FOLDER               1548
#define ID_EXPORT_ZIP                   1549
#define ID_EXPORT_FOLDER                1550
#define ID_CREATE_SUB_COLLECTIONS       1551
#define ID_REGISTER_LICENSE             1552
#define ID_LIBRARY_SETTING              1601
#define IDD_GET_INFO_DLG                15071
#define IDD_GET_INFO_SUMMARY_TAB_DLG    15072
#define IDD_GET_INFO_INFO_TAB_DLG       15073
#define IDD_ADD_TAGS_DLG                15074
#define IDD_CATEGORIES_SELECTION_DLG    15076
#define IDD_OPTIONS_CHECK_FOR_UPDATES_DLG 15077
#define IDD_OPTIONS_INTERFACE_DLG       15078
#define IDD_OPTIONS_FILE_MANAGER_DLG    15079
#define IDD_OPTIONS_GENERAL_DLG1        15080
#define IDD_OPTIONS_UNSORTED_FILTER_DLG 15080
#define IDD_PREVIEW_DLG                 15081
#define IDD_EXPORT_FOLDER_DLG           15082
#define IDD_ABOUT_TAB_LICENSE           15083
#define IDD_IMPORT_FROM_FOLDER_DLG      15084
#define IDD_OPTIONS_PROPERTIES_DLG      15085
#define IDD_RENAME_FILE_DLG1            15086
#define IDD_OPTIONS_PDF_DLG             15087
#define IDD_PDF_PROPERTIES_FRAME        15088
#define IDD_OPTIONS_DLG1                15089
#define IDD_PDF_PROPERTIES_DLG          15089
#define IDD_GET_INFO_PDF_TAB_DLG        15090
#define IDD_RENAME_FILE_DLG2            15091
#define IDD_RENAME_COLLECTION_DLG       15091
#define IDD_IMPORTLIBRARY_FROM_ZIP_DLG  15092
#define IDD_EXPORT_FOLDER_DLG1          15093
#define IDD_CONTENT_SEARCH_DLG          15093
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_VIEW_APPLOOK_2000            32826
#define ID_VIEW_APPLOOK_XP              32827
#define ID_VIEW_APPLOOK_2003            32828
#define ID_VIEW_APPLOOK_WIN_XP          32829
#define ID_VIEW_APPLOOK_VS2005          32830
#define ID_VIEW_APPLOOK_2007            32831
#define ID_VIEW_APPLOOK_2007_1          32832
#define ID_VIEW_APPLOOK_2007_2          32833
#define ID_VIEW_APPLOOK_2007_3          32834
#define ID_VIEW_APPLOOK_VS2008          32835
#define ID_FILE_NEWCOLLECTION           32850
#define ID_FILE_NEWSMARTCOLLECTION      32851
#define ID_FILE_ADDFILE                 32852
#define ID_FILE_ADDFOLDER               32853
#define ID_FILE_ADDWATCHEDFOLDER        32854
#define ID_FILE_RENAME                  32855
#define ID_EDIT_DELETE                  32856
#define ID_EDIT_RENAME                  32857
#define ID_EDIT_SELECTALL               32858
#define ID_EDIT_SELECT                  32859
#define ID_Menu                         32860
#define ID_VIEW_DETAILS32861            32861
#define ID_VIEW_SHOWBROWSER             32862
#define ID_VIEW_SHOWTAGS                32863
#define ID_TOOLS_MANAGETAGS             32864
#define ID_TOOLS_MANAGECATEGORIES       32865
#define ID_TOOLS_MANAGEWATCHEDFOLDERS   32866
#define ID_TOOLS_CONSOLIDATELIBRARY     32867
#define ID_TOOLS_OPTIONS                32868
#define ID_HELP_HELP                    32869
#define ID_HELP_LICENSE                 32870
#define ID_HELP_CHECKFORUPDATE          32871
#define ID_NEW_COLLECTION               32872
#define ID_TOOLBAR_PANEL                32873
#define ID_DUMMY_ADDFILE                32874
#define ID_DUMMY_ADDFOLDER              32875
#define ID_DUMMY_ADDWATCHEDFOLDER       32876
#define ID_DUMMY_NEWCOLLECTION          32877
#define ID_DUMMY_NEWSMARTCOLLECTION     32878
#define ID_NEW_SMART_COLLECTION         32880
#define ID_ADD_WATCHED_FOLDER           32882
#define ID_DUMMY_BACKUP                 32883
#define ID_DUMMY_ATTACHTOEMAIL          32884
#define ID_DUMMY_GETINFO                32885
#define ID_BACKUP_TOCD                  32886
#define ID_BACKUP_TOSTORAGEDEVICEORSERVICE 32887
#define ID_BACKUP_TO_CD_DVD             32888
#define ID_BACKUP_TO_STORAGE_DEVICE     32889
#define ID_ATTACH_TO_EMAIL              32890
#define ID_GET_INFO                     32891
#define ID_DUMMY_ALL                    32892
#define ID_DUMMY_TITLE                  32893
#define ID_DUMMY_AUTHOR                 32894
#define ID_DUMMY_SUBJECT                32895
#define ID_DUMMY_TAGS                   32896
#define ID_FIND_ALL                     32897
#define ID_FIND_TITLE                   32898
#define ID_FIND_AUTHOR                  32899
#define ID_FIND_SUBJECT                 32900
#define ID_FIND_TAGS                    32901
#define ID_DUMMY_GETINFO32902           32902
#define ID_DUMMY_PRINT                  32903
#define ID_OPEN                         32904
#define ID_DUMMY_OPENWIDTH              32905
#define ID_DUMMY_ATTACHTOEMAIL32906     32906
#define ID_DUMMY_BACKUP32907            32907
#define ID_DUMMY_ADDTOCOLLECTION        32908
#define ID_DUMMY_SHOWINWINDOWSEXPLORER  32909
#define ID_DUMMY_EXPLORER               32910
#define ID_DUMMY_COPY                   32911
#define ID_DUMMY_DELETE                 32912
#define ID_DUMMY_RENAME                 32913
#define ID_BROWSER_PANEL                32914
#define ID_SHOW_BROWSER                 32915
#define ID_TAGS_PANEL                   32916
#define ID_MANAGE_TAGS                  32917
#define ID_MANAGE_CATEGORIES            32918
#define ID_DOCUMENT_FILE_LIST           32920
#define ID_DOCUMENT_THUMB_LIST          32921
#define ID_MANAGE_WATCHED_FOLDERS       32922
#define ID_LICENSE                      32923
#define ID_DUMMY_OPENBENUBIRD           32924
#define ID_DUMMY_SHOW                   32925
#define ID_DUMMY_HIDENOTIFICATIONS      32926
#define ID_DUMMY_OPTIONS                32927
#define ID_DUMMY_CHECKFORUPDATES        32928
#define ID_DUMMY_EXIT                   32929
#define ID_OPEN_BENUBIRD                32930
#define ID_SHOW_NOTIFICATIONS           32931
#define ID_HIDE_NOTIFICATIONS           32932
#define ID_CHECK_FOR_UPDATES            32933
#define ID_EXIT                         32934
#define ID_ADDTOCOLLECTION_COLLECTION1  32935
#define ID_DUMMY_FILENAME               32936
#define ID_DUMMY_TITLE32937             32937
#define ID_DUMMY_AUTHOR32938            32938
#define ID_DUMMY_SUBJECT32939           32939
#define ID_DUMMY_DESCRIPTION            32940
#define ID_DUMMY_CATEFORY               32941
#define ID_DUMMY_TAGS32942              32942
#define ID_DUMMY_SIZE                   32943
#define ID_DUMMY_TYPE                   32944
#define ID_DUMMY_DATECREATED            32945
#define ID_DUMMY_DATEMODIFIED           32946
#define ID_DUMMY_DATEADDED              32947
#define ID_DUMMY_LASTOPENED             32948
#define ID_DUMMY_ATTRIBUTES             32949
#define ID_METADATA_GETINFO             32950
#define ID_HEADER_FILENAME              32951
#define ID_HEADER_TITLE                 32952
#define ID_HEADER_AUTHOR                32953
#define ID_HEADER_SUBJECT               32954
#define ID_HEADER_TAGS                  32955
#define ID_HEADER_COLLECTIONS           32956
#define ID_HEADER_TYPE                  32957
#define ID_HEADER_SIZE                  32958
#define ID_HEADER_CATEGORY              32959
#define ID_HEADER_PATH                  32960
#define ID_HEADER_DATE_CREATED          32961
#define ID_HEADER_DATE_MODIFIED         32962
#define ID_HEADER_DATE_ADDED            32963
#define ID_HEADER_LAST_OPENED           32964
#define ID_HEADER_ATTRIBUTES            32965
#define ID_HEADER_COMMENTS              32966
#define ID_SHOW_IN_WIN_EXPLORER         32969
#define ID_METADATA_INFO                32970
#define ID_PRINT                        32971
#define ID_SHARE_EMAIL                  32972
#define ID_EXPORTASFOLDER_EXPOTYASZIPARCHIVE 32973
#define ID_DUMMY_BURNTOCD               32974
#define ID_DUMMY_DELETE32975            32975
#define ID_DUMMY_RENAME32976            32976
#define ID_DELETE_COLLECTION            32977
#define ID_RENAME_COLLECTION            32978
#define ID_DELETE_FILE                  32979
#define ID_PREVIEW_PANEL                32980
#define ID_VIEW_FILELIST                32981
#define ID_SELECT_ALL                   32982
#define ID_FILE_SELECT_ALL              32982
#define ID_DUMMY_COMMENTS               32983
#define ID_DUMMY_COLLECTIONS            32985
#define ID_FILTERS_TREE                 33000
#define ID_COLLECTIONS_TREE             33001
#define ID_SMART_COLLECTIONS_TREE       33002
#define ID_TABS_WINDOW                  33003
#define ID_COLLECTION_PANEL             33004
#define ID_DUMMY_EXPORTTO               33005
#define ID_EXPORTTO_ZIPPACKAGE          33006
#define ID_EXPORTTO_FOLDER              33007
#define ID_EXPORTTO_ZIPPACKAGE33008     33008
#define ID_EXPORTTO_FOLDER33009         33009
#define ID_EXPORT                       33010
#define ID_DUMMY_EDIT                   33010
#define ID_IMPORT                       33011
#define ID_SMART_COLLECTION_EDIT        33011
#define ID_RENAME_FILE                  33012
#define ID_COPY_FILE                    33013
#define ID_DUMMY_CREATECOLLECTIONFROMSELECTION 33016
#define ID_CREATECOLLECTIONFROMSELECTION 33017
#define ID_DUMMY_CREATECOLLECTIONFROMSELECTION33018 33018
#define ID_CREATECOLLECTIONFROMSELECTION33018 33019
#define ID_DUMMY_OPENWITH               33020
#define ID_DUMMY_CONVERTTOPDF           33021
#define ID_CONVERTTOPDF_FILE            33022
#define ID_DUMMY_SHOWMODIFIEDFILES      33023
#define ID_SHOWMODIFIEDFILES            33024
#define ID_DUMMY_CLOSEFILEFOREDITING    33025
#define ID_CLOSE                        33026
#define ID_DUMMY_ADDTOCOLLECTION33027   33027
#define ID_DUMMY_REMOVEFROMCOLLECTION   33028
#define ID_DUMMY_ADDTOTAGS              33029
#define ID_DUMMY_REMOVEFROMTAGS         33030
#define ID_ADD_TO_COLLECTION            33031
#define ID_REMOVE_FROM_COLLECTION       33032
#define ID_ADD_TO_TAGS                  33033
#define ID_REMOVE_FROM_TAGS             33034
#define ID_DUMMY_CREATESUB              33035
#define ID_DUMMY_RENAME33036            33036
#define ID_SMART_COLLECTION_RENAME      33037
#define ID_FREE_UPGRADE                 33038
#define ID_PREVIEWPDF                   33040
#define ID_SWITCH_REPOSITORY            33041
#define ID_OPEN_WORKSPACE               33042
#define ID_CLOSE_WORKSPACE              33043
#define ID_SWITCH_DIRECT                33044
#define ID_SELECT_ALL_FILES             35001
#define ID_DUMMY_SELECTEDFILES          35004
#define ID_STATUSBAR_SELECTEDFILES      35005
#define ID_PDF_SAVE                     35006
#define ID_PDF_PROPERTIES               35007
#define ID_PDF_PRINT                    35008
#define ID_PDF_PREVPAGE                 35009
#define ID_PDF_NEXTPAGE                 35010
#define ID_PDF_ZOONIN                   35011
#define ID_PDF_ZOOMOUT                  35012
#define ID_DOC_PROPERTIES               35013
#define ID_PDF_ZOOM_IN                  35014
#define ID_PDF_ZOOM_OUT                 35015
#define ID_PDF_SAVE_AS                  35016
#define ID_PDF_ENDPAGE                  35017
#define ID_PDF_HOMEPAGE                 35018
#define ID_PDF_PAGES                    35019
#define ID_PDF_PAGEEDIT                 35020
#define ID_PDF_ZOOMCOMBO                35021
#define ID_PDF_SAVE_EXPORT              35022
#define ID_OPEN_DEFAULT_VIEWER          35023
#define ID_DUMMY_                       35023
#define ID_PDF_DEFAULT_VIEWER           35024
#define ID_DUMMY_35024                  35024
#define ID_DUMMY_RESETTHEORDER          35025
#define ID_HEADER_RESET_ORDER           35026
#define ID_DUMMY_CONTENT                35027
#define ID_FIND_CONTENT                 35028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         35029
#define _APS_NEXT_CONTROL_VALUE         1417
#define _APS_NEXT_SYMED_VALUE           200
#endif
#endif
