#pragma once

// Constants
#define kOptions _T("Options")

//General
#define kLoadOnStartup				_T("LoadOnStartup")
#define kShowIconInSystemTray		_T("ShowIconInSystemTray")
#define kMinimizeToSystemTray		_T("MinimizeToSystemTray")
#define kIgnoreTmpFiles				_T("IgnoreTmpFiles")
#define kIgnoreWinFiles				_T("IgnoreWinFiles")
#define kIgnoreLnkFiles				_T("IgnoreLnkFiles")
#define kIgnoreNoExtFiles			_T("IgnoreNoExtFiles")
#define kUseRepository				_T("UseRepository")
#define kIgnoreSVNFiles				_T("IgnoreSVNFiles")

//Check for updates
#define kCheckForUpdates			_T("CheckForUpdates")
#define kNextCheckForUpdates		_T("NextCheckForUpdates")

//Notifications
#define kNotifyWhenAddSilently		_T("NotifyWhenAddSilently")
#define kNotifyWhenAddDirectly		_T("NotifyWhenAddDirectly")
#define kNotifyWhenUpdateAvailable	_T("NotifyWhenUpdateAvailable")

//File manager
//#define kFilesFolderLocation		_T("FilesFolderLocation")

/*
#define kCopyFilesToFolder			_T("CopyFilesToFolder")
#define kActionAfterCopy			_T("ActionAfterCopy")
*/

//Workspace & Repository
#define kRepositoryFolder			_T("RepositoryFolder")
#define kRepositoryActionOnAdd		_T("RepositoryActionOnAdd")
#define kWorkspaceFolder			_T("WorkspaceFolder")
#define kWorkspaceActionOnChange	_T("WorkspaceActionOnChange")

//Metadata auto-genaration
#define kAutoGenerateDontOverwrite	_T("AutoGenerateDontOverwrite")
#define kAutoGenerateTitle			_T("AutoGenerateTitle")
#define kAutoGenerateTags			_T("AutoGenerateTags")
#define kAutoGenerateAuthor			_T("AutoGenerateAuthor")
#define kAutoGenerateSubject		_T("AutoGenerateSubject")
#define kMaximumFiles				_T("Maximumfiles")

//PDF
#define kPDFHyperlink				_T("PDFHyperlink")
#define kPDFBookmark				_T("PDFBookmark")
#define kPDFEmbedSubset				_T("PDFEmbedSubset")
#define kPDFDisplayInfoTab			_T("PDFDisplayInfoTab")
#define kPDFRenderWithQuickPDF			_T("PDFRenderWithQuickPDF")
#define kPDFUseInfo					_T("PDFUseInfo")
#define kPDFGSettings				_T("PDFGSettings")
#define kPDFOutputFolder			_T("PDFOutputFolder")

#define kPDFDefaultProfileKey		_T("SOFTWARE\\Softland\\novaPDF\\Printers\\Add to Benubird PDF as PDF\\Profiles\\Default Profile")
#define kPDFProfileKey				_T("SOFTWARE\\Softland\\novaPDF\\Printers\\Add to Benubird PDF as PDF\\Profiles")
#define kPDFGeneralKey				_T("SOFTWARE\\Softland\\novaPDF Desktop OEM 6\\Add to Benubird PDF as PDF")
